CREATE TABLE Products (
  ProductId INT IDENTITY PRIMARY KEY,
  Name NVARCHAR(100) NOT NULL,
  SKU NVARCHAR(50) NOT NULL,
  Description NVARCHAR(400),
  QuantityInStock INT NOT NULL DEFAULT 0,
  Threshold INT NOT NULL DEFAULT 0,
  Price DECIMAL(18,2) NOT NULL DEFAULT 0
);
CREATE TABLE Orders (
  OrderId INT IDENTITY PRIMARY KEY,
  OrderDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CustomerId NVARCHAR(64) NOT NULL,
  OrderStatus NVARCHAR(32) NOT NULL DEFAULT 'Created'
);
CREATE TABLE OrderItems (
  OrderItemId INT IDENTITY PRIMARY KEY,
  OrderId INT NOT NULL FOREIGN KEY REFERENCES Orders(OrderId) ON DELETE CASCADE,
  ProductId INT NOT NULL,
  Quantity INT NOT NULL,
  UnitPrice DECIMAL(18,2) NOT NULL
);
